adminUser:
  username: admin
enableDocker: false
gitProvider: github
gpg: {}
pipelineUser:
  github:
    host: github.com
    username: jenkins-x-versions-bot-test
    email: jenkins-x@googlegroups.com
